### PR TITLE
added CloudFormation Custom Resource template to AWSLambdaPSCore PowerShell module templates

### PR DESCRIPTION
**Pull request by scrthq**
*Issue #, if available:* N/A

*Description of changes:* Added a new template to provide a base for creating Lambda-backed custom resources for CloudFormation written in PowerShell.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by normj** [comment]
Thanks for the pull request. We really appreciate helping fill out our templates selection. I have merged it in the dev branch which means it will go out with the next release of the AWSLambdaPSCore module.

The templates are also hosted online which `Get-AWSPowerShellLambdaTemplate` will use by default if you are online. The online configuration has been updated so as long as you are online you will see your new template.

```
PS C:\Users\normj> Get-AWSPowerShellLambdaTemplate

Template                     Description
--------                     -----------
Basic                        Bare bones script
CloudFormationCustomResource PowerShell handler base for use with CloudFormation custom resource events
CodeCommitTrigger            Script to process AWS CodeCommit Triggers
DetectLabels                 Use Amazon Rekognition service to tag image files in S3 with detected labels.
KinesisStreamProcessor       Script to be process a Kinesis Stream
S3Event                      Script to process S3 events
SNSSubscription              Script to be subscribed to an SNS Topic
SQSQueueProcessor            Script to be subscribed to an SQS Queue
```

**Comment by scrthq** [comment]
Awesome!! Thanks for the quick review and response, Norm!

I'll be sure to send over any additional use cases I come up with that may be worthy of a template!

**Comment by normj** [comment]
Version 1.1.0 of AWSLambdaPSCore now ships with this template. Thanks for the effort!

**Comment by normj** [comment]
Not sure why GitHub didn't auto close this but everything has been merged into master so I manually closed it.

**Pull request closed without merging**
