### PR TITLE
Added additional S3 Event blueprints

### PR DESCRIPTION
**Pull request by austoonz**
*Issue #, if available:*
There is no issue related to this.

*Description of changes:*
Added additional PowerShell Lambda Blueprints for S3 Events. These include samples for:

- S3 -> SNS -> Lambda
- S3 -> SNS -> SQS -> Lambda
- S3 -> SQS -> Lambda

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by normj** [comment]
The design of the templates was each template would have a single Lambda function template. This PR adds 3 additional Lambda function to the same template. That would potential overall whelm a new PS Lambda user wondering what should they do with all of these files.

For each template make a separate folder and entry in the `ps-lambda-blueprint-manifest.json` file.

**Comment by austoonz** [comment]
Yep I’m fine with that Norm. I was actually deciding which way to go when I was putting them together. I’ll get an update to this and the SQS one.

**Comment by austoonz** [comment]
Norm - I've updated the commit in my fork with the updates as requested.

**Comment by austoonz** [comment]
I modified "S3EventToSNSToSQS" to support both RAW and non-RAW SNS Subscriptions.

**Comment by normj** [comment]
Merge to dev branch

**Pull request merged**
