### PR TITLE
Add new section templates & repositories to README.md

### PR DESCRIPTION
**Pull request by pharindoko**
*Description of changes:*
added new section to readme file

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by pharindoko** [comment]
Hello, anyone here to help me ? :)

**Comment by pharindoko** [comment]
@normj 
Hey Norm can you check my request please ?

**Comment by pharindoko** [comment]
Anyone here ? :)

**Comment by normj** [comment]
Thanks for the PR!

**Pull request merged**
