### PR TITLE
convenience improvements:

### PR DESCRIPTION
**Pull request by aidanjryan**
*Issue #, if available:* none

*Description of changes:*

* add --path parameter to specify specific function path
* when the requested function definition is bad, report its error on the execution response

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by normj** [comment]
Thanks for the PR. I'm good taking the code changes but there is a lot of whitespace changes due to I suspect line ending difference that is causing me merge pain. Can resubmit the PR fixing the line endings?

**Comment by aidanjryan** [comment]
Hi Norm, thanks for responding so quickly. Those changes are actually removing trailing whitespace, no line endings are changed. I'm happy to revert those if you wish.

**Comment by aidanjryan** [comment]
OK, should be a lot cleaner now :)

**Comment by normj** [comment]
Much better and just in time as I was pushing out the bits. This went out just now as version 0.9.1.

**Comment by aidanjryan** [comment]
Cool thanks for the quick turnaround!

**Pull request merged**
