### PR TITLE
Added parsing of the function node in the serverless.yml

### PR DESCRIPTION
**Pull request by samueleresca**
*Description of changes:*
Added parsing for the function based `serverless.yml` definition. The YAML parser now can handle the following syntax :
```
# serverless.yml
service: myService

provider:
  name: aws
  runtime: dotnetcore2.1
  memorySize: 512 # will be inherited by all functions

functions:
  createfunction:
    handler: DotNetServerless.Lambda::DotNetServerless.Lambda.Functions.CreateItemFunction::Ru
```
As described in the getting started present in the serverless framework web site

Should we create a dedicated parser class for that? 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by normj** [comment]
How is this PR different then the one I merged into the dev branch? https://github.com/aws/aws-lambda-dotnet/pull/357

Also it looks like something went wrong with the gitignore. Files under ` Tools/LambdaTestTool/Amazon.Lambda.TestTool/ExternalCommands/App` should not have been checked in as those are the build artifacts from `Amazon.Lambda.TestTool.ExternalCommands`.

**Comment by samueleresca** [comment]
Hi @normj , sorry I haven't noticed the Dlls in the App folder. Now it should be fine. The difference between this and the #357 is in the format of the `serverless.yaml` file.

- The #357 parses the following resource based syntax of the `serverless.yaml`:
[https://github.com/aws/aws-lambda-dotnet/blob/dev/Tools/LambdaTestTool/LambdaFunctions/ServerlessTemplateYamlExample/serverless.yaml](https://github.com/aws/aws-lambda-dotnet/blob/dev/Tools/LambdaTestTool/LambdaFunctions/ServerlessTemplateYamlExample/serverless.yaml)

- This one parses the following syntax :
[https://github.com/aws/aws-lambda-dotnet/blob/b8bb2811695b4d4cafc412ecd3a98a9b3b5ecf15/Tools/LambdaTestTool/LambdaFunctions/ServerlessFunctionTemplateYamlExample/serverless.yml](https://github.com/aws/aws-lambda-dotnet/blob/b8bb2811695b4d4cafc412ecd3a98a9b3b5ecf15/Tools/LambdaTestTool/LambdaFunctions/ServerlessFunctionTemplateYamlExample/serverless.yml)


Let me know,
Samuele

**Comment by slang25** [comment]
Just to remove any doubt for readers, `ServerlessTemplateYamlExample` is the "AWS Serverless Transform", i.e. vanilla CloudFormation.
`ServerlessFunctionTemplateYamlExample` is the [serverless framework](https://serverless.com/). Who knew that would get confusing 😄

**Comment by normj** [comment]
In case you were worried about not getting feedback in a bit. I'm on Christmas vacation and will catch up with this when I'm back in the office.

**Comment by normj** [comment]
Merged into dev so it will go out with the next release of the tool. I'll comment back on the PR when the release happens.

**Comment by samueleresca** [comment]
@normj  Thanks 👍

**Comment by normj** [comment]
Version 0.9.0 was released today with this PR. Thanks for the help.

**Pull request merged**
