### PR TITLE
Scheduled events

### PR DESCRIPTION
**Pull request by exocom**
*Issue #, if available:*
#16
*Description of changes:*
Added missing class for Cloud Watch Events - Scheduled Events.
https://docs.aws.amazon.com/lambda/latest/dg/eventsources.html#eventsources-scheduled-event

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by joaoasrosa** [comment]
AWS, there is any timeline to merge this PR? I'm looking for the same solution, and I want to avoid to duplicate code with the event.

**Comment by normj** [comment]
I'm trying to get to it as soon as I can. Its just a busy time with AWS re:Invent coming soon.

**Comment by joaoasrosa** [comment]
> I'm trying to get to it as soon as I can. Its just a busy time with AWS re:Invent coming soon.

Thanks to let us know!

**Comment by normj** [comment]
Thanks for your patience. This has been merged into the dev branch to go out with the next release.

**Comment by normj** [comment]
Version 1.0.0 of the Amazon.Lambda.CloudWatchEvents package was released today. Thanks for your all help getting this package out.

**Pull request merged**
