### PR TITLE
Constructor for JsonSerializer

### PR DESCRIPTION
**Pull request by rfrerebe**

### CODE REVIEW

**Comment by normj** [comment]
This looks good. I'll try and find some more time soon to take a deeper dive.

**Comment by normj** [comment]
I have this merged in with our local repo. I'll get it out soon, I'm just queuing up a couple more changes first.

**Comment by normj** [comment]
Version 1.2.0 of Amazon.Lambda.Serialization.Json was just released with this pull request. Sorry it took a bit of time to get out. It got stuck behind some other queued up work.

**Comment by rfrerebe** [comment]
You are welcome.
Let me know if you need any help in the future.

**Pull request merged**
