### PR TITLE
feat: added contracts for cognito pre token generation v2_0

### PR DESCRIPTION
**Pull request by ernest-folch-fleksy**
*Description of changes:*

Added contracts for Cognito Pre token generation V2_0 as described on https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ernest-folch-fleksy** [comment]
Pull request created as suggested by @ashishdhingra on discussion https://github.com/aws/aws-lambda-dotnet/discussions/1650

**Review by normj — APPROVED** [review]
Looks good. If you could bump the version number in the project file to 2.3.0 that would be great.

**Comment by ernest-folch-fleksy** [comment]
> Looks good. If you could bump the version number in the project file to 2.3.0 that would be great.

@normj CognitoEvents version number bumped to 2.3.0

**Comment by normj** [comment]
> > Looks good. If you could bump the version number in the project file to 2.3.0 that would be great.
> 
> @normj CognitoEvents version number bumped to 2.3.0

Thanks, let me get somebody else on the team to do a second pass and then we will get this released.

**Review by muhammad-othman — APPROVED** [review]

**Comment by normj** [comment]
Thanks for the PR. The change has just been released. There was another PR included that triggered the version to be 3.0.0. https://github.com/aws/aws-lambda-dotnet/blob/master/RELEASE.CHANGELOG.md#release-2024-01-18

**Pull request merged**
