### PR TITLE
Improved F# templates

### PR DESCRIPTION
**Pull request by sharptom**
*Issue #, if available:* N/A

*Description of changes:*

This PR aims to improve the F# templates by:
- formatting the code as recommended by the [F# style guide];
- using F# idiomatic constructs where appropriate.

Progress tracking:
- [x] Lambda Detect Image Labels
- [x] Lambda Empty Function
- [x] Lambda Simple DynamoDB Function
- [x] Lambda Simple Kinesis Function
- [x] Lambda Simple S3 Function
- [x] Lambda ASP.NET Core Web API
- [x] Serverless Detect Image Labels
- [x] Lambda Empty Serverless
- [x] Lambda Giraffe Web App
- [x] Serverless Simple S3 Function
- [x] Step Functions Hello World

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

[F# style guide]: https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/

### CODE REVIEW

**Comment by normj** [comment]
Awesome, I appreciate the help. My F# skills are at the learning stage. I'm traveling now but later this week I can take a deeper look into the changes.

**Comment by sharptom** [comment]
No need to hurry, it will be some weeks before I finish reviewing all templates. Currently, my changes consist mostly in removing C# leftovers.

I am no F# expert but I'm glad if I can help. 🙂

**Comment by normj** [comment]
Thanks I'll take a look soon. I'll have to merge it into another release we have coming very soon which affects the blueprints.

**Comment by normj** [comment]
Version 3.2.0 of Amazon.Lambda.Templates and version 1.14.4 of the AWS Toolkit for Visual Studio went out with these changes as part of today's .NET Core 2.1 release.

**Pull request merged**
