### PR TITLE
Add the word "Lambda" to templates that don't have it. Issue 1396.

### PR DESCRIPTION
**Pull request by bjhogan**
*Issue #, if available:*
1396
*Description of changes:*

Some templates didn't have the word "Lambda" in them, so they don't show when dotnet new lambda --list is run.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by normj** [comment]
We updated the [README](https://github.com/aws/aws-lambda-dotnet#blueprints) file to how to properly search for our templates. I don't think we need to prefix every template with the word Lambda so I'm going to close the PR.

**Comment by bjhogan** [comment]
Do we have any feedback on how users discover new templates? If they filter on the word "Lambda", as the instructions used to say, they may not find some of the more recent templates.

**Comment by normj** [comment]
I haven't heard any feedback one way or the other. You following the comment in the README file was the first comment I had heard about this in the years that comment has been in the README.

**Comment by normj** [comment]
Sorry I should have been more explicit. The main reason I don't really want to do this is it makes the names quite long. In Visual Studio the project wizard would likely start to cut off the meaningful part of the names of some of these projects to force the Lambda prefix in the name.

**Comment by bjhogan** [comment]
What if the word "Lambda" was added to the end of the name, that way command line users could easily find the templates.

**Pull request closed without merging**
