### PR TITLE
Make http status code available

### PR DESCRIPTION
**Pull request by kabaluk**
Issue #1468

Made HttpStatusCode available for ease of testing.

Common Usage scenario:
Testing if you got the right Status result from a function returning IHttpResult.
Currently no easy way of checking the actual result.
Exposing the HttpStatusCode solves the below scenario.

    public class Functions
    {
        [LambdaFunction]
        [HttpApi(LambdaHttpMethod.Get, "/resource/{type}")]
        public IHttpResult GetResponse(string type, ILambdaContext context)
        {
            return type == "good" ?
                HttpResults.Ok() :
                HttpResults.BadRequest();
        }
    }

    public class HtttpResultsStatusCodeUsage
    {
        [Fact]
        public void UsageOfIHttpResultStatusCode()
        {
            var sut = new Functions();

            var result = sut.GetResponse("good", null);

            Assert.Equal(HttpStatusCode.OK, result.StatusCode);

            result = sut.GetResponse("not good", null);

            Assert.Equal(HttpStatusCode.BadRequest, result.StatusCode);
        }
    }

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by kabaluk** [comment]
Common Usage scenario:
Testing if you got the right Status result from a function returning IHttpResult.
Currently no easy way of checking the actual result.
Exposing the HttpStatusCode solves the below scenario.

`
 public class Functions
    {
        [LambdaFunction]
        [HttpApi(LambdaHttpMethod.Get, "/resource/{type}")]
        public IHttpResult GetResponse(string type, ILambdaContext context)
        {
            return type == "good" ?
                HttpResults.Ok() :
                HttpResults.BadRequest();
        }
    }

public class HtttpResultsStatusCodeUsage
    {
        [Fact]
        public void UsageOfIHttpResultStatusCode()
        {
            var sut = new Functions();

            var result = sut.GetResponse("good", null);

            Assert.Equal(HttpStatusCode.OK, result.StatusCode);

            result = sut.GetResponse("not good", null);

            Assert.Equal(HttpStatusCode.BadRequest, result.StatusCode);
        }
    }
`

**Review by normj — APPROVED** [review]
Looks good!

**Review by ashovlin — APPROVED** [review]
Thanks! "Source Generator CI" is expected to fail because this is from a fork, but not concerned.

**Comment by chrispaynter** [comment]
Nice!

**Comment by normj** [comment]
Version 0.13.3 is out with this PR. Thanks again for the PR!

**Pull request merged**
