### PR TITLE
Support Cognito Pre Token Generation Event

### PR DESCRIPTION
**Pull request by GuzzoLM**
*Issue #732*

*Description of changes: Add class for Cognito Pre Token Generation Lambda Trigger Parameters*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jon-armen** [comment]
This PR would be covered by / conflict with #1051

**Comment by ashishdhingra** [comment]
@GuzzoLM Thanks for your contribution. Is it fine to close this PR as duplicate of https://github.com/aws/aws-lambda-dotnet/pull/1051?

**Comment by jon-armen** [comment]
> @GuzzoLM Thanks for your contribution. Is it fine to close this PR as duplicate of #1051?

@ashishdhingra , do you have any updates when #1051 may be merged and released?

**Comment by michaelakin** [comment]
Please review and merge this or 1051 soon.  The contract in the Nuget package Amazon.Lambda.CognitoEvents is not valid any longer and causes an exception.  Can you please remove this  package from Nuget?

**Comment by ashishdhingra** [comment]
> Please review and merge this or 1051 soon. The contract in the Nuget package Amazon.Lambda.CognitoEvents is not valid any longer and causes an exception. Can you please remove this package from Nuget?

The PR https://github.com/aws/aws-lambda-dotnet/pull/1051 needs to have integration testing done to rule out any post-release issues.

**Review by normj — APPROVED** [review]

**Comment by normj** [comment]
I ended up merging and releasing PR #1051 instead of this PR which also implemented this feature along with many other Cognito event types. That PR has been released as part of version 2.1.0 of Amazon.Lambda.CognitoEvents.

**Pull request merged**
